-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categories
(
    categoryid serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT categories_pkey PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS public.orderitems
(
    orderitemid uuid NOT NULL DEFAULT gen_random_uuid(),
    orderid uuid NOT NULL,
    productid uuid NOT NULL,
    quantity integer DEFAULT 1,
    price numeric(12, 2),
    CONSTRAINT orderitems_pkey PRIMARY KEY (orderitemid)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    orderid uuid NOT NULL DEFAULT gen_random_uuid(),
    userid uuid NOT NULL,
    orderdate timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    totalamount numeric(12, 2),
    CONSTRAINT orders_pkey PRIMARY KEY (orderid)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    paymentid uuid NOT NULL DEFAULT gen_random_uuid(),
    orderid uuid NOT NULL,
    amount numeric(12, 2),
    paymentmethod character varying(50) COLLATE pg_catalog."default",
    paymentstatus character varying(50) COLLATE pg_catalog."default",
    paymentdate timestamp without time zone,
    CONSTRAINT payments_pkey PRIMARY KEY (paymentid)
);

CREATE TABLE IF NOT EXISTS public.productimages
(
    imageid uuid NOT NULL DEFAULT gen_random_uuid(),
    productid uuid NOT NULL,
    imageurl text COLLATE pg_catalog."default" NOT NULL,
    isprimary boolean DEFAULT false,
    uploadedat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT productimages_pkey PRIMARY KEY (imageid)
);

CREATE TABLE IF NOT EXISTS public.products
(
    productid uuid NOT NULL DEFAULT gen_random_uuid(),
    categoryid integer NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(100) COLLATE pg_catalog."default",
    model character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    price numeric(12, 2) NOT NULL,
    quantity integer DEFAULT 0,
    condition character varying(50) COLLATE pg_catalog."default",
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT products_pkey PRIMARY KEY (productid)
);

CREATE TABLE IF NOT EXISTS public.reports
(
    reportid serial NOT NULL,
    reportmonth date NOT NULL,
    totalsales numeric(12, 2),
    totalorders integer,
    newcustomers integer,
    completedswaps integer,
    outstandingpayments numeric(12, 2),
    generatedat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reports_pkey PRIMARY KEY (reportid)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    roleid serial NOT NULL,
    rolename character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (roleid),
    CONSTRAINT roles_rolename_key UNIQUE (rolename)
);

CREATE TABLE IF NOT EXISTS public.swaprequests
(
    swaprequestid uuid NOT NULL DEFAULT gen_random_uuid(),
    userid uuid NOT NULL,
    currentdevicebrand character varying(100) COLLATE pg_catalog."default",
    currentdevicemodel character varying(100) COLLATE pg_catalog."default",
    devicecondition text COLLATE pg_catalog."default",
    faultdescription text COLLATE pg_catalog."default",
    desireddevice character varying(200) COLLATE pg_catalog."default",
    estimatedtopupamount numeric(12, 2),
    deviceimage1 text COLLATE pg_catalog."default",
    deviceimage2 text COLLATE pg_catalog."default",
    deviceimage3 text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT swaprequests_pkey PRIMARY KEY (swaprequestid)
);

CREATE TABLE IF NOT EXISTS public.userroles
(
    userid uuid NOT NULL,
    roleid integer NOT NULL,
    CONSTRAINT userroles_pkey PRIMARY KEY (userid, roleid)
);

CREATE TABLE IF NOT EXISTS public.users
(
    userid uuid NOT NULL DEFAULT gen_random_uuid(),
    firstname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phonenumber character varying(20) COLLATE pg_catalog."default",
    passwordhash text COLLATE pg_catalog."default" NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    isactive boolean DEFAULT true,
    CONSTRAINT users_pkey PRIMARY KEY (userid),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.orderitems
    ADD CONSTRAINT orderitems_orderid_fkey FOREIGN KEY (orderid)
    REFERENCES public.orders (orderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orderitems
    ADD CONSTRAINT orderitems_productid_fkey FOREIGN KEY (productid)
    REFERENCES public.products (productid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_orderid_fkey FOREIGN KEY (orderid)
    REFERENCES public.orders (orderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.productimages
    ADD CONSTRAINT productimages_productid_fkey FOREIGN KEY (productid)
    REFERENCES public.products (productid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_categoryid_fkey FOREIGN KEY (categoryid)
    REFERENCES public.categories (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.swaprequests
    ADD CONSTRAINT swaprequests_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.userroles
    ADD CONSTRAINT userroles_roleid_fkey FOREIGN KEY (roleid)
    REFERENCES public.roles (roleid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.userroles
    ADD CONSTRAINT userroles_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;